QuizManagementSystem/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView
from Quizapp import urls
from rest_framework.authtoken.views import obtain_auth_token
from accounts.views import login_view,home,user_logout
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-token-auth/',obtain_auth_token),
    path('',include('Quizapp.urls')),
    path('accounts/login/',login_view,name='login'),
    path('home',home),
    path('logout/', user_logout, name='logout'),
    path('api-auth/',include('rest_framework.urls')),
    


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Quizapp/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token 
from . import views
urlpatterns=[
    path('topics/',views.topiclist.as_view()),
    path('topics_list/',views.alltopics.as_view()),
    path('particulartopic/<str:id>',views.particular_topic_update,name='particulartopic'),
    path('delete_topic/<str:id>',views.delete_topic,name='delete_topic'),
    path('subjects_list/',views.SubjectsList.as_view()),
    path('add_subject/',views.AddSubject.as_view()),
    path('delete_subject/<str:id>',views.delete_subject,name='delete_subject'),
    path('subject_update/<str:id>',views.particular_subject_update,name='subject_update'),
    path('add_class/',views.AddClass.as_view()),
    path('class_list/',views.ClassList.as_view()),
    path('delete_class/<str:id>',views.delete_class,name='delete_class'),
    path('class_update/<str:id>',views.particular_class_update,name='class_update'),
    path('add_quiz/',views.AddQuiz.as_view()),
    path('quiz_list/',views.QuizList.as_view()),
    path('quiz_update/<str:id>',views.quiz_update,name='quiz_update'),
    path('quiz_delete/<str:id>',views.quiz_delete,name='quiz_delete'),
    path('questions_details/<str:id>',views.questions_details.as_view(),name='questions_details'),
    path('manage_questions/',views.manage_questions.as_view()),
    path('update_manage_questions_mcqs/<str:id>',views.update_given_mcqs_data.as_view(),name='update_manage_questions_mcqs'),
    path('manage_theory_question/',views.manage_theory_question.as_view(),name='manage_theory_question'),
    path('update_question/<str:id>',views.update_question.as_view(),name='update_question'),
    path('delete_manage_questions_mcqs/<str:id>',views.delete_manage_questions_mcqs.as_view(),name='delete_manage_questions_mcqs'),
    path('delete_theory_question/<str:id>',views.delete_theory_question.as_view(),name='delete_theory_question'),
    path('add_question/',views.AddQuestions.as_view()),
    path('questions_list/',views.QuestionsList.as_view()),
    path('delete_questions/<str:id>',views.delete_questions,name='delete_questions'),
    path('addmcqs/',views.AddMcqs.as_view()),
    path('mcqs_list/',views.McqsList.as_view()),
    path('addtheory/',views.AddTheory.as_view()),
    path('theory_list/',views.TheoryList.as_view()),
    path('delete_theory/<str:id>',views.delete_theory,name='delete_theory'),
    path('addanswerchoice/',views.AddAnswerChoice.as_view()),
    path('answerchoice_list/',views.AnswerChoiceList.as_view()),
    path('addcorrectanswer/',views.AddCorrectAnswer.as_view()),
    path('correctanswerlist/',views.CorrectAnswerList.as_view()),
    path('delete_correctanswer/<str:id>',views.delete_correctanswer,name='delete_correctanswer'),
    path('load/', views.load_subjects.as_view(), name='load'),
    path('subjectload/', views.subjectload.as_view(), name='subjectload'),
    path('questions/',views.questions.as_view()),
    path('',views.quizpage.as_view(),name='main_page'),
    path('quiz_section/',views.teacher_quiz.as_view(),name='quiz_section'),
    path('conduct_quiz/',views.conduct_quiz().as_view(),name='conduct_quiz'),
    path('endresult/',views.result,name='endresult'),
    path('result/',views.user_result().as_view(),name='result'),
    path('timer/',views.timer,name='timer'),
    path('add_school/',views.add_school.as_view(),name='add_school'),
    path('update_school/<str:id>',views.particular_school_update,name='particular_school_update'),
    path('delete_school/<str:id>',views.delete_school,name='delete_school'),
    path('schools_list/',views.all_school.as_view(),name='all_school'),







    
]

Quizapp/models.py
from django.db import models
import secrets
from django.db.models.signals import post_save
import uuid
from django.dispatch import receiver
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token
from django.http import HttpResponse
from django.conf import settings
from uuid import UUID
# Create your models here.

class Class(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=20,null=False)
    code = models.CharField(max_length=15,null=False,blank=False)
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Classes"


class Subject(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name     = models.CharField(max_length=15,null=False)
    code     = models.CharField(max_length=15,null=False,blank=False)
    class_id = models.ForeignKey(
        to = Class,
        on_delete = models.CASCADE,
    )

    def __str__(self):
        return (self.name)
    class Meta:
        verbose_name_plural = "Subjects"


class Topic(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name     = models.CharField(max_length=15,null=False)
    code     = models.CharField(max_length=15,null=False,blank=False)
    Sub_id   = models.ForeignKey(
        to = Subject,
        on_delete = models.CASCADE,
    )
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "Topics"

class Quiz(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    Class      = models.ForeignKey(
        to=Class,
        on_delete=models.CASCADE,
        blank=False,null=False,

    )
    subject    = models.ForeignKey(
        to=Subject,
        on_delete=models.CASCADE,
        blank=False,null=False,
    )
    topic      = models.OneToOneField(
        to=Topic,
        on_delete=models.CASCADE,
        blank=False,null=False,
    )
    name       = models.CharField(max_length=15,unique=True,blank=False,null=False,)
    code       = models.CharField(max_length=15,null=False,blank=False)
    created_by = models.CharField(max_length=15 ,blank=False,null=False,)
    
    def __str__(self):
        return (self.name)
    class Meta:
        verbose_name_plural = "Quizes"


class Questions(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    questype = models.CharField(max_length=15,null=False)
    marks    = models.IntegerField(null=False)
    quiz_id  = models.ForeignKey(
        to=Quiz,
        on_delete=models.CASCADE
        )
    def __str__(self):
        return (self.questype)

    class Meta:
        verbose_name_plural = "Questions"


class Mcqs(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    mcq_question    = models.TextField(max_length=500,null=False)
    mcq_picture     = models.FileField(upload_to='images/',null=True,blank=True)
    question_id     = models.ForeignKey(
        to=Questions,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return str(self.mcq_question)
    class Meta:
        verbose_name_plural = "MCQS"    

class Theory(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    theory_question = models.TextField(max_length=500,null=False)
    correct_ans     = models.CharField(max_length=200,null=False)
    theory_pic      = models.FileField(upload_to='images/',null=True,blank=True)
    question_id     = models.ForeignKey(
         to=Questions,
         on_delete=models.CASCADE
        )
    def __str__(self):
        return (self.theory_question) 
    class Meta:
        verbose_name_plural = "Theories"


class AnswerChoice(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    answer  = models.CharField(max_length=200,null=False)
    mcqs_id = models.ForeignKey(
        to=Mcqs,
        on_delete=models.CASCADE
    )
    def __str__(self):
        return (self.answer)
    class Meta:
        verbose_name_plural = "Answer's Choices"


class CorrectAnswer(models.Model):
    correct_ans = models.ForeignKey(to=AnswerChoice,on_delete=models.CASCADE)
    mcqs_id     = models.ForeignKey(
        to=Mcqs,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return str((self.correct_ans))
    class Meta:
        verbose_name_plural = "Correct Answers"

        
class School(models.Model):
    name    = models.CharField(max_length=200)
    address = models.CharField(max_length=150)
    

Quizapp/forms.py
from django import forms
from .models import *

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = '__all__'
class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields ='__all__'
class ClassForm(forms.ModelForm):
    class Meta:
        model = Class
        fields ='__all__'

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = '__all__'
class SchoolForm(forms.ModelForm):
    class Meta:
        model = School
        fields = '__all__'
    
        

Quizapp/templates/quizes/addquiz.html
{% extends 'master.html' %}
{% load rest_framework %}
{% block content %}

<div class="container-fluid">
<div class="card">
<div class="card-header">Add Quiz</div>
<div class="card-body">
        
        <form class="form-hozizontal" method="POST"  class="panel-body">

                {% csrf_token %}
                {% render_form serializer %}
                <input type="submit" class="btn btn-primary " id="submit_btn"  value="Save">
                
        </form>
<br>
<br>
</div>
</div>
</div>


<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script> 
$(document).ready(function(){
    $('select[name="Class"]').change(function(){    
    var  url = '{% url "load" %}'
    var classid = $(this).val();
    $.ajax({    
        type: "GET",                   
        url: url,                   
        data: {
          'classes': classid,       
        }, 
        success: function (data) {   
        console.log(data)
        $('select[name="subject"]').html(data); 
        },error : function(e) { 
        alert('an error occured');
        }
        });
});


$('select[name="subject"]').change(function(){    
        var  url = '{% url "subjectload" %}'
        var subjectid = $(this).val();
        console.log(subjectid)
        $.ajax({    
        type: "GET",                   
        url: url,                   
        data: {
        'subjects': subjectid,       
        },
        success: function (data) {   
        $('select[name="topic"]').html(data); 
        },error : function(e) { 
        alert('an error occured');
        }
        });
});

}) 
window.onload=function(){
        $("input[name='created_by']").val('{{request.user}}');
        $("select[name='Class']").val('------------');
        $("select[name='subject']").val('------------');
        $("select[name='topic']").val('------------');

        $("input[name='code']").val('{{token}}');

        


};
</script>



{% endblock %}

Quizapp/templates/quizes/allquiz.html
{% extends 'master.html' %}
{% block content %}
<style>
#myInput {
  background-image: url('/css/searchicon.png');
  background-position: 10px 10px;
  background-repeat: no-repeat;
  width: 100%;
  font-size: 16px;
  padding: 12px 20px 12px 40px;
  border: 1px solid #ddd;
  margin-bottom: 12px;
}
</style>
<div class="card">
    <div class="card-header">
      List of Quizes
    </div>
    <div class="card-body">
        <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for quizes.." title="Type in a name">
<div class="table-responsive">
        <table class="table table-bordered" id="myTable">
          <thead class="text-center">
            <tr>
              <th>Quiz Name</th>
              <th>Class</th>
              <th>Subject</th>
              <th>Topic</th>
              <th>Code</th>
              <th>Created by</th>
              <th>Actions</th>

            </tr>
          </thead>
          <tbody>
            {% for quiz in quizes %}
            <tr class="text-center">
                <td> <a href="{% url 'questions_details' id=quiz.id %}">{{quiz.name}}</a>  </td>
                <td>{{quiz.Class}}</td>
                <td>{{quiz.subject}}</td>
                <td>{{quiz.topic.name}}</td>
                <td>{{quiz.code}}</td>
                <td>{{quiz.created_by}}</td>

                

                <td><a href="{% url 'quiz_update' id=quiz.id  %}"><i class="fa fa-edit"> </i></a> <a href="{% url 'quiz_delete' id=quiz.id  %}"> <span style="margin-left: 20%;"><i class="fa fa-trash"> </i></span></a> </td>
    
    
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
    </div>
    </div>
    

    <script>
        function myFunction() {
          var input, filter, table, tr, td, i, txtValue;
          input = document.getElementById("myInput");
          filter = input.value.toUpperCase();
          table = document.getElementById("myTable");
          tr = table.getElementsByTagName("tr");
          for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td) {
              txtValue = td.textContent || td.innerText;
              if (txtValue.toUpperCase().indexOf(filter) > -1) {
                tr[i].style.display = "";
              } else {
                tr[i].style.display = "none";
              }
            }       
          }
        }
        </script>
{% endblock %}

Quizapp/templates/quizes/updatequiz.html
{% extends 'master.html' %}
{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if error %}
{{ error }}
{% endif %}


<style> 
        input[type=text] {
          color: #6e707e;
          width: 100%;
          padding: 8px 20px;
          border-color: #d1d3e2;
          border-style: solid;
          border-radius: 5px;
          border-width: thin;
        }
        #id_Class,#id_subject,#id_topic
        {
          color: #6e707e;
            width: 100%;
          padding: 8px 20px;
          border-color: #d1d3e2;
          border-style: solid;
          border-radius: 5px;
          border-width: thin;
        }
</style>


<div class="card">
    <div class="card-header">Update Quiz</div>
    <div class="card-body">
            <form class="form-hozizontal" method="POST" class="panel-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-primary" value="Save">
            </form>
    </div>
    </div>



    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>   
<script> 
$(document).ready(function(){
    $('select[name="Class"]').change(function(){    
    var  url = '{% url "load" %}'
    var classid = $(this).val();
    $.ajax({    
        type: "GET",                   
        url: url,                   
        data: {
          'classes': classid,       
        }, 
        success: function (data) {   
        console.log(data)
        $('select[name="subject"]').html(data); 
        },error : function(e) { 
        alert('an error occured');
        }
        });
});


$('select[name="subject"]').change(function(){    
        var  url = '{% url "subjectload" %}'
        var subjectid = $(this).val();
        console.log(subjectid)
        $.ajax({    
        type: "GET",                   
        url: url,                   
        data: {
        'subjects': subjectid,       
        },
        success: function (data) {   
        $('select[name="topic"]').html(data); 
        },error : function(e) { 
        alert('an error occured');
        }
        });
});





}) 

</script>
{% endblock %}